"""Write xposed-module/dev-keys.properties from ~/.specter-ipcheck.json, so a LOCAL build comes up with the
reputation keys already filled in.

    python xposed-module/make-dev-keys.py

The output is GITIGNORED and the repo is PUBLIC — no key may ever enter the tree. A DISTRIBUTABLE build is
simply one made without this file: every BuildConfig field is then empty and the app shows "Not set", which
is already the correct UI for a user who has to bring their own keys. Delete the file to go back to that.
"""
import json
import sys
from pathlib import Path

# properties key (== the Android pref name) -> key in ~/.specter-ipcheck.json
MAP = {
    "ipqs_key": "ipqs_key",
    "abuseipdb_key": "abuse_key",
    "getipintel_contact": "getipintel_contact",
    "scamalytics_user": "scamalytics_user",
    "scamalytics_key": "scamalytics_key",
}
OUT = Path(__file__).resolve().parent / "dev-keys.properties"


def main() -> int:
    src = Path.home() / ".specter-ipcheck.json"
    if not src.exists():
        print(f"no {src} — nothing to seed; the build will ship empty key fields")
        return 1
    cfg = json.loads(src.read_text("utf-8"))
    lines = ["# GENERATED by make-dev-keys.py from ~/.specter-ipcheck.json. Gitignored — never commit.",
             "# Delete this file to build a distributable APK with no keys baked in."]
    have = []
    for prop, cfg_key in MAP.items():
        v = (cfg.get(cfg_key) or "").strip()
        if v:
            have.append(prop)
        # Properties escaping: only a backslash needs it for these values (no ':' or '=' in a key/email).
        lines.append(f"{prop}={v.replace(chr(92), chr(92) * 2)}")
    OUT.write_text("\n".join(lines) + "\n", "utf-8")
    print(f"wrote {OUT.name} with {len(have)} key(s): {', '.join(have) or 'none'}")
    print("this APK is for THIS machine — do not distribute it")
    return 0


if __name__ == "__main__":
    sys.exit(main())
