"""Write xposed-module/dev-keys.properties from ~/.specter-ipcheck.json.

    python xposed-module/make-dev-keys.py

The output is gitignored and written 0600. A build made WITH the file compiles the values into BuildConfig
and the app writes them into prefs on first launch; a build made WITHOUT it gets empty strings and the app
shows "Not set". Delete the file to return to that state.
"""
import json
import os
import sys
from pathlib import Path

# properties key (== the Android pref name) -> key in ~/.specter-ipcheck.json
MAP = {
    "ipqs_key": "ipqs_key",
    "abuseipdb_key": "abuse_key",
    "getipintel_contact": "getipintel_contact",
    "scamalytics_user": "scamalytics_user",
    "scamalytics_key": "scamalytics_key",
}
OUT = Path(__file__).resolve().parent / "dev-keys.properties"


def main() -> int:
    src = Path.home() / ".specter-ipcheck.json"
    if not src.exists():
        print(f"no {src} — nothing to seed; the build will ship empty key fields")
        return 1
    cfg = json.loads(src.read_text("utf-8"))
    lines = ["# GENERATED by make-dev-keys.py from ~/.specter-ipcheck.json. Gitignored — never commit.",
             "# Delete this file to build a distributable APK with no keys baked in."]
    have = []
    for prop, cfg_key in MAP.items():
        v = (cfg.get(cfg_key) or "").strip()
        if v:
            have.append(prop)
        # Properties escaping: only a backslash needs it for these values (no ':' or '=' in a key/email).
        lines.append(f"{prop}={v.replace(chr(92), chr(92) * 2)}")
    # Owner-only, created 0600 from the start rather than chmod'd after — this file holds LIVE API keys,
    # and .gitignore keeps it out of the repo but does nothing about another local account reading it.
    # Written to a private temp file in the same directory then atomically replaced, so a reader never
    # sees a half-written file and never sees one with default permissions.
    #
    # HONEST LIMIT: the mode is POSIX. On Windows os.open's mode only toggles the read-only attribute and
    # access follows inherited NTFS ACLs, so this does NOT make the file private there — it will still
    # show as -rw-r--r--. On Windows the protection is the location, not this call.
    tmp = OUT.with_suffix(".properties.tmp")
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    os.replace(tmp, OUT)
    print(f"wrote {OUT.name} with {len(have)} key(s): {', '.join(have) or 'none'}")
    print("this APK is for THIS machine — do not distribute it")
    return 0


if __name__ == "__main__":
    sys.exit(main())
